import { FileHelper, T, z } from '@start9labs/start-sdk'
import { i18n } from '../i18n'
import { sdk } from '../sdk'
import {
  chain,
  defaultWallet,
  rpcallowip,
  rpcbind,
  rpccookiefile,
  rpcPort,
} from '../utils'

// INI coercion helpers (INI parsing yields strings; duplicate keys -> arrays).
const iniString = z
  .union([z.array(z.string()).transform((a) => a.at(-1)!), z.string()])
  .optional()
  .catch(undefined)

const iniNumber = z
  .union([
    z.array(z.string()).transform((a) => Number(a.at(-1))),
    z.string().transform(Number),
    z.number(),
  ])
  .optional()
  .catch(undefined)

const iniBoolean = z
  .union([
    z.string().transform((s) => !!Number(s)),
    z.number().transform((n) => !!n),
    z.boolean(),
  ])
  .optional()
  .catch(undefined)

/**
 * Typed model for elements.conf.
 *
 * Enforced (not user-editable) keys keep the node reachable from the StartOS
 * internal network and pin it to the Liquid mainnet sidechain:
 *   chain=liquidv1, server=1, listen=1, txindex=1, validatepegin=0,
 *   rpcbind=0.0.0.0, rpcallowip=0.0.0.0/0, rpcport=7041, rpccookiefile=.cookie
 *
 * `rpcuser`/`rpcpassword` are optional: when present they let a dependent
 * authenticate without reading the cookie file. The cookie file is always
 * generated by elementsd and is the primary credential surface.
 */
export const shape = z.object({
  // Enforced
  chain: z.literal(chain).catch(chain),
  server: z.literal(true).catch(true),
  listen: z.literal(true).catch(true),
  txindex: z.literal(true).catch(true),
  validatepegin: z.literal(false).catch(false),
  rpcbind: z.literal(rpcbind).catch(rpcbind),
  rpcallowip: z.literal(rpcallowip).catch(rpcallowip),
  rpcport: z.literal(rpcPort).catch(rpcPort),
  rpccookiefile: z.literal(rpccookiefile).catch(rpccookiefile),

  // Optional RPC auth for dependents that prefer user/pass over the cookie.
  rpcuser: iniString,
  rpcpassword: iniString,

  // User-tunable
  dbcache: iniNumber,
  rpcthreads: iniNumber,
  rpcworkqueue: iniNumber,
  maxconnections: iniNumber,
  fallbackfee: iniString,
})

export type ElementsConf = z.infer<typeof shape>

const { InputSpec, Value } = sdk

export const fullConfigSpec = sdk.InputSpec.of({
  raw: Value.hidden(shape),
  dbcache: Value.number({
    name: i18n('Database Cache'),
    description: i18n(
      'How much RAM (in MiB) to allocate for caching during sync. Higher values speed up initial sync.',
    ),
    required: false,
    default: null,
    min: 0,
    integer: true,
    units: 'MiB',
    footnote: `${i18n('Default')}: 450 MiB`,
  }),
  rpcthreads: Value.number({
    name: i18n('RPC Threads'),
    description: i18n('Number of threads for handling RPC calls.'),
    required: false,
    default: null,
    min: 1,
    max: 64,
    integer: true,
    footnote: `${i18n('Default')}: 4`,
  }),
  rpcworkqueue: Value.number({
    name: i18n('RPC Work Queue'),
    description: i18n('Depth of the work queue used to service RPC calls.'),
    required: false,
    default: null,
    min: 8,
    max: 256,
    integer: true,
    footnote: `${i18n('Default')}: 16`,
  }),
  maxconnections: Value.number({
    name: i18n('Maximum Connections'),
    description: i18n('Maximum number of peer connections to maintain.'),
    required: false,
    default: null,
    min: 0,
    integer: true,
    footnote: `${i18n('Default')}: 125`,
  }),
})

function fileToForm(
  input: ElementsConf,
): T.DeepPartial<typeof fullConfigSpec._TYPE> {
  return {
    raw: input ?? {},
    dbcache: input.dbcache ?? null,
    rpcthreads: input.rpcthreads ?? null,
    rpcworkqueue: input.rpcworkqueue ?? null,
    maxconnections: input.maxconnections ?? null,
  }
}

function formToFile(
  input: T.DeepPartial<typeof fullConfigSpec._TYPE>,
): ElementsConf {
  const { raw, dbcache, rpcthreads, rpcworkqueue, maxconnections } = input
  return {
    ...raw,
    // Enforced
    chain,
    server: true,
    listen: true,
    txindex: true,
    validatepegin: false,
    rpcbind,
    rpcallowip,
    rpcport: rpcPort,
    rpccookiefile,
    // Preserve any generated RPC auth from raw.
    rpcuser: raw?.rpcuser,
    rpcpassword: raw?.rpcpassword,
    // Tunables
    dbcache: dbcache ?? undefined,
    rpcthreads: rpcthreads ?? undefined,
    rpcworkqueue: rpcworkqueue ?? undefined,
    maxconnections: maxconnections ?? undefined,
    fallbackfee: raw?.fallbackfee,
  }
}

function stringifyPrimitives(a: unknown): any {
  if (a && typeof a === 'object') {
    if (Array.isArray(a)) return a.map(stringifyPrimitives)
    return Object.fromEntries(
      Object.entries(a)
        .filter(([, v]) => v !== undefined)
        .map(([k, v]) => [k, stringifyPrimitives(v)]),
    )
  } else if (typeof a === 'boolean') {
    return a ? 1 : 0
  }
  return a
}

export const elementsConfFile = FileHelper.ini(
  {
    base: sdk.volumes.main,
    subpath: '/elements.conf',
  },
  fullConfigSpec.partialValidator,
  { bracketedArray: false },
  {
    onRead: (a) => fileToForm(shape.parse(a)),
    onWrite: (a) => stringifyPrimitives(formToFile(a)),
  },
)

// re-export so seedFiles/actions can reference the wallet name in one place
export { defaultWallet }
